/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as OpenBetsRouteImport } from './routes/open-bets'
import { Route as ApiEloSyncRouteImport } from './routes/api.elo-sync'
import { Route as RunRunIdOportunidadesRouteImport } from './routes/run.$runId.oportunidades'
import { Route as RunRunIdProcessamentoRouteImport } from './routes/run.$runId.processamento'
import { Route as RunRunIdResultadoRouteImport } from './routes/run.$runId.resultado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenBetsRoute = OpenBetsRouteImport.update({
  id: '/open-bets',
  path: '/open-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEloSyncRoute = ApiEloSyncRouteImport.update({
  id: '/api/elo-sync',
  path: '/api/elo-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdOportunidadesRoute = RunRunIdOportunidadesRouteImport.update({
  id: '/run/$runId/oportunidades',
  path: '/run/$runId/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdProcessamentoRoute = RunRunIdProcessamentoRouteImport.update({
  id: '/run/$runId/processamento',
  path: '/run/$runId/processamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdResultadoRoute = RunRunIdResultadoRouteImport.update({
  id: '/run/$runId/resultado',
  path: '/run/$runId/resultado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/open-bets': typeof OpenBetsRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/open-bets': typeof OpenBetsRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/open-bets': typeof OpenBetsRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/open-bets'
    | '/api/elo-sync'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/open-bets'
    | '/api/elo-sync'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/open-bets'
    | '/api/elo-sync'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  OpenBetsRoute: typeof OpenBetsRoute
  ApiEloSyncRoute: typeof ApiEloSyncRoute
  RunRunIdOportunidadesRoute: typeof RunRunIdOportunidadesRoute
  RunRunIdProcessamentoRoute: typeof RunRunIdProcessamentoRoute
  RunRunIdResultadoRoute: typeof RunRunIdResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-bets': {
      id: '/open-bets'
      path: '/open-bets'
      fullPath: '/open-bets'
      preLoaderRoute: typeof OpenBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elo-sync': {
      id: '/api/elo-sync'
      path: '/api/elo-sync'
      fullPath: '/api/elo-sync'
      preLoaderRoute: typeof ApiEloSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/oportunidades': {
      id: '/run/$runId/oportunidades'
      path: '/run/$runId/oportunidades'
      fullPath: '/run/$runId/oportunidades'
      preLoaderRoute: typeof RunRunIdOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/processamento': {
      id: '/run/$runId/processamento'
      path: '/run/$runId/processamento'
      fullPath: '/run/$runId/processamento'
      preLoaderRoute: typeof RunRunIdProcessamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/resultado': {
      id: '/run/$runId/resultado'
      path: '/run/$runId/resultado'
      fullPath: '/run/$runId/resultado'
      preLoaderRoute: typeof RunRunIdResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  OpenBetsRoute: OpenBetsRoute,
  ApiEloSyncRoute: ApiEloSyncRoute,
  RunRunIdOportunidadesRoute: RunRunIdOportunidadesRoute,
  RunRunIdProcessamentoRoute: RunRunIdProcessamentoRoute,
  RunRunIdResultadoRoute: RunRunIdResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
