/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as DiagnosticoRouteImport } from './routes/diagnostico'
import { Route as OpenBetsRouteImport } from './routes/open-bets'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ApiAnalysisWorkerRouteImport } from './routes/api.analysis-worker'
import { Route as ApiEloSyncRouteImport } from './routes/api.elo-sync'
import { Route as ApiFiveDollarMaintenanceRouteImport } from './routes/api.five-dollar-maintenance'
import { Route as ApiModelValidationRouteImport } from './routes/api.model-validation'
import { Route as ApiPushDispatchRouteImport } from './routes/api.push-dispatch'
import { Route as DraftDraftIdValidacaoRouteImport } from './routes/draft.$draftId.validacao'
import { Route as RunRunIdOportunidadesRouteImport } from './routes/run.$runId.oportunidades'
import { Route as RunRunIdProcessamentoRouteImport } from './routes/run.$runId.processamento'
import { Route as RunRunIdResultadoRouteImport } from './routes/run.$runId.resultado'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoRoute = DiagnosticoRouteImport.update({
  id: '/diagnostico',
  path: '/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenBetsRoute = OpenBetsRouteImport.update({
  id: '/open-bets',
  path: '/open-bets',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalysisWorkerRoute = ApiAnalysisWorkerRouteImport.update({
  id: '/api/analysis-worker',
  path: '/api/analysis-worker',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEloSyncRoute = ApiEloSyncRouteImport.update({
  id: '/api/elo-sync',
  path: '/api/elo-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFiveDollarMaintenanceRoute =
  ApiFiveDollarMaintenanceRouteImport.update({
    id: '/api/five-dollar-maintenance',
    path: '/api/five-dollar-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiModelValidationRoute = ApiModelValidationRouteImport.update({
  id: '/api/model-validation',
  path: '/api/model-validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPushDispatchRoute = ApiPushDispatchRouteImport.update({
  id: '/api/push-dispatch',
  path: '/api/push-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftDraftIdValidacaoRoute = DraftDraftIdValidacaoRouteImport.update({
  id: '/draft/$draftId/validacao',
  path: '/draft/$draftId/validacao',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdOportunidadesRoute = RunRunIdOportunidadesRouteImport.update({
  id: '/run/$runId/oportunidades',
  path: '/run/$runId/oportunidades',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdProcessamentoRoute = RunRunIdProcessamentoRouteImport.update({
  id: '/run/$runId/processamento',
  path: '/run/$runId/processamento',
  getParentRoute: () => rootRouteImport,
} as any)
const RunRunIdResultadoRoute = RunRunIdResultadoRouteImport.update({
  id: '/run/$runId/resultado',
  path: '/run/$runId/resultado',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/conta': typeof ContaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/open-bets': typeof OpenBetsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/analysis-worker': typeof ApiAnalysisWorkerRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/five-dollar-maintenance': typeof ApiFiveDollarMaintenanceRoute
  '/api/model-validation': typeof ApiModelValidationRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/draft/$draftId/validacao': typeof DraftDraftIdValidacaoRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/conta': typeof ContaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/open-bets': typeof OpenBetsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/analysis-worker': typeof ApiAnalysisWorkerRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/five-dollar-maintenance': typeof ApiFiveDollarMaintenanceRoute
  '/api/model-validation': typeof ApiModelValidationRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/draft/$draftId/validacao': typeof DraftDraftIdValidacaoRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/conta': typeof ContaRoute
  '/diagnostico': typeof DiagnosticoRoute
  '/open-bets': typeof OpenBetsRoute
  '/privacidade': typeof PrivacidadeRoute
  '/api/analysis-worker': typeof ApiAnalysisWorkerRoute
  '/api/elo-sync': typeof ApiEloSyncRoute
  '/api/five-dollar-maintenance': typeof ApiFiveDollarMaintenanceRoute
  '/api/model-validation': typeof ApiModelValidationRoute
  '/api/push-dispatch': typeof ApiPushDispatchRoute
  '/draft/$draftId/validacao': typeof DraftDraftIdValidacaoRoute
  '/run/$runId/oportunidades': typeof RunRunIdOportunidadesRoute
  '/run/$runId/processamento': typeof RunRunIdProcessamentoRoute
  '/run/$runId/resultado': typeof RunRunIdResultadoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/conta'
    | '/diagnostico'
    | '/open-bets'
    | '/privacidade'
    | '/api/analysis-worker'
    | '/api/elo-sync'
    | '/api/five-dollar-maintenance'
    | '/api/model-validation'
    | '/api/push-dispatch'
    | '/draft/$draftId/validacao'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/conta'
    | '/diagnostico'
    | '/open-bets'
    | '/privacidade'
    | '/api/analysis-worker'
    | '/api/elo-sync'
    | '/api/five-dollar-maintenance'
    | '/api/model-validation'
    | '/api/push-dispatch'
    | '/draft/$draftId/validacao'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/conta'
    | '/diagnostico'
    | '/open-bets'
    | '/privacidade'
    | '/api/analysis-worker'
    | '/api/elo-sync'
    | '/api/five-dollar-maintenance'
    | '/api/model-validation'
    | '/api/push-dispatch'
    | '/draft/$draftId/validacao'
    | '/run/$runId/oportunidades'
    | '/run/$runId/processamento'
    | '/run/$runId/resultado'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ContaRoute: typeof ContaRoute
  DiagnosticoRoute: typeof DiagnosticoRoute
  OpenBetsRoute: typeof OpenBetsRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ApiAnalysisWorkerRoute: typeof ApiAnalysisWorkerRoute
  ApiEloSyncRoute: typeof ApiEloSyncRoute
  ApiFiveDollarMaintenanceRoute: typeof ApiFiveDollarMaintenanceRoute
  ApiModelValidationRoute: typeof ApiModelValidationRoute
  ApiPushDispatchRoute: typeof ApiPushDispatchRoute
  DraftDraftIdValidacaoRoute: typeof DraftDraftIdValidacaoRoute
  RunRunIdOportunidadesRoute: typeof RunRunIdOportunidadesRoute
  RunRunIdProcessamentoRoute: typeof RunRunIdProcessamentoRoute
  RunRunIdResultadoRoute: typeof RunRunIdResultadoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico': {
      id: '/diagnostico'
      path: '/diagnostico'
      fullPath: '/diagnostico'
      preLoaderRoute: typeof DiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-bets': {
      id: '/open-bets'
      path: '/open-bets'
      fullPath: '/open-bets'
      preLoaderRoute: typeof OpenBetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analysis-worker': {
      id: '/api/analysis-worker'
      path: '/api/analysis-worker'
      fullPath: '/api/analysis-worker'
      preLoaderRoute: typeof ApiAnalysisWorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/elo-sync': {
      id: '/api/elo-sync'
      path: '/api/elo-sync'
      fullPath: '/api/elo-sync'
      preLoaderRoute: typeof ApiEloSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/five-dollar-maintenance': {
      id: '/api/five-dollar-maintenance'
      path: '/api/five-dollar-maintenance'
      fullPath: '/api/five-dollar-maintenance'
      preLoaderRoute: typeof ApiFiveDollarMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/model-validation': {
      id: '/api/model-validation'
      path: '/api/model-validation'
      fullPath: '/api/model-validation'
      preLoaderRoute: typeof ApiModelValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/push-dispatch': {
      id: '/api/push-dispatch'
      path: '/api/push-dispatch'
      fullPath: '/api/push-dispatch'
      preLoaderRoute: typeof ApiPushDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$draftId/validacao': {
      id: '/draft/$draftId/validacao'
      path: '/draft/$draftId/validacao'
      fullPath: '/draft/$draftId/validacao'
      preLoaderRoute: typeof DraftDraftIdValidacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/oportunidades': {
      id: '/run/$runId/oportunidades'
      path: '/run/$runId/oportunidades'
      fullPath: '/run/$runId/oportunidades'
      preLoaderRoute: typeof RunRunIdOportunidadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/processamento': {
      id: '/run/$runId/processamento'
      path: '/run/$runId/processamento'
      fullPath: '/run/$runId/processamento'
      preLoaderRoute: typeof RunRunIdProcessamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/run/$runId/resultado': {
      id: '/run/$runId/resultado'
      path: '/run/$runId/resultado'
      fullPath: '/run/$runId/resultado'
      preLoaderRoute: typeof RunRunIdResultadoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ContaRoute: ContaRoute,
  DiagnosticoRoute: DiagnosticoRoute,
  OpenBetsRoute: OpenBetsRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ApiAnalysisWorkerRoute: ApiAnalysisWorkerRoute,
  ApiEloSyncRoute: ApiEloSyncRoute,
  ApiFiveDollarMaintenanceRoute: ApiFiveDollarMaintenanceRoute,
  ApiModelValidationRoute: ApiModelValidationRoute,
  ApiPushDispatchRoute: ApiPushDispatchRoute,
  DraftDraftIdValidacaoRoute: DraftDraftIdValidacaoRoute,
  RunRunIdOportunidadesRoute: RunRunIdOportunidadesRoute,
  RunRunIdProcessamentoRoute: RunRunIdProcessamentoRoute,
  RunRunIdResultadoRoute: RunRunIdResultadoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
